### ISSUE TITLE
problem with ie7

### ISSUE THREAD

**Issue by Zweer** [arian/mootools-form-upload#1]
Hi, there is a problem with ie7: when it creates a clone of the input row, the first clone is created well, while the second crashes the whole ie instance...

i'm trying to resolve the problem...you'll be notified when i'll find a solution!!!

cya, and really a great script!!! you've resolved all my problems!!!

**Comment by Zweer** [comment]
ok, it's a known issue https://mootools.lighthouseapp.com/projects/2706/tickets/1196-cloning-element-twice-crashes-ie7

i've resolved on line 93 putting: 

``` javascript
var newRow = rowClone.clone(true, true);
```

instead of: 

``` javascript
var newRow = rowClone.clone();
```

also on line 89 you have to put ',' at the end, not ';' (multiple var declaration)...

hope it will be usefull, cya!!!

**Comment by arian** [comment]
Ooh, awesome, i will fix it. The crash seems to be an bug in the clone method though.
