### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by Zweer** [arian/mootools-form-upload#2]
Hi, again me (you are gonna hating me ^^")

i've found that if i drag two files in the form (or add them with the "Browse" button), and i submit twice, the second time it sends four file, instead of two, because it doesn't reset the form after the first submit...

the same thing appens it i delete those files and put other files: it always submit also the first files because no reset was done...

i've searched for a way to reset the Request.File object, but haven't find so far (i have to be honest, i've spend not so mutch time in trying to understand it :)

cya, and again good job!!! (:

**Comment by arian** [comment]
probably the request method would look like:

```
this.formData = new FormData();
```

Good catch though!

**Comment by Zweer** [comment]
ah, ok thanks, but is there a way to set it in the "complete" event? 
because i've try to refer to "this.formData" but, as i thought, it's an undefined var in Form.Upload
at the end of Request.File.send() it should be put something like the initialization (or a reset, dunno exactly how FormData works, my bad)

**Comment by arian** [comment]
It's fixed now as in the pull request #3
