### ISSUE TITLE
Script timeout

### ISSUE THREAD

**Issue by questra06** [arian/mootools-form-upload#5]
With less then 50 files it works well.
When I try to upload 400 files the form post action has never been executed. 

<script type="text/javascript" src="Form.MultipleFileInput.js"></script>

<script type="text/javascript" src="Form.Upload.js"></script>

<script type="text/javascript" src="Request.File.js"></script>

<script type="text/javascript" src="iFrameFormRequest.js"></script>

<script type="text/javascript">
    window.addEvent('domready', function(){
        var upload = new Form.Upload('file', {
            dropMsg: "drag fileshere",
            onComplete: function(){
                showAlertUpload('Upload complete');
            }
        });
    });
</script>

<div id="pageContent" style="padding:10px;">
        <form id="upload" action="/global/obj/documenti/upload_robot.asp?<%=EnCrypt("masterKey")%>=<%=EnCrypt(masterId)%>&<%=EnCrypt("parentKey")%>=<%=EnCrypt(parentId)%>" method="POST" enctype="multipart/form-data"">
            <table style="width:100%">
                <tr>
                    <td>Select files:<input type="file" id="file" name="file[]" multiple></td>
                </tr>            
                <tr>
                    <td style="text-align:center">
                        <input type="submit" value="Upload files" />
                    </td>         
                </tr>
            </table>                   
        </form>
    <%end if%>
</div>

**Comment by arian** [comment]
In that case you probably should upload the files in chunks: http://www.html5rocks.com/en/tutorials/file/xhr2/#toc-example-slicingfiles

I'm not going to implement this myself any time soon, but I could accept pull requests :)
